version: '3.1'
services:
  edge:
    image: 'edge:latest'
    build: ./edge/
    ports:
      - '5683:5683/udp'
    depends_on:
      - resources-db
      - metrics-db
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      DOCKER_INFLUXDB_INIT_ORG: '${DOCKER_INFLUXDB_INIT_ORG}'
      DOCKER_INFLUXDB_INIT_BUCKET: '${DOCKER_INFLUXDB_INIT_BUCKET}'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: '${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}'
  resources-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'resources-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
  metrics-db:
    image: influxdb
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - 'metrics-data:/var/lib/influxdb2'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: '${DOCKER_INFLUXDB_INIT_MODE}'
      DOCKER_INFLUXDB_INIT_USERNAME: '${DOCKER_INFLUXDB_INIT_USERNAME}'
      DOCKER_INFLUXDB_INIT_PASSWORD: '${DOCKER_INFLUXDB_INIT_PASSWORD}'
      DOCKER_INFLUXDB_INIT_ORG: '${DOCKER_INFLUXDB_INIT_ORG}'
      DOCKER_INFLUXDB_INIT_BUCKET: '${DOCKER_INFLUXDB_INIT_BUCKET}'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: '${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}'
  grafana:
    image: 'grafana-configured:latest'
    build: ./grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
    depends_on:
      - resources-db
      - metrics-db
volumes:
  resources-data: null
  metrics-data: null
  grafana-data: null
